<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_25</name>
   <tag></tag>
   <elementGuidId>b9abe875-041f-4199-bfec-85d6b6bd7eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>html/body/div/div[1]/table/tbody/tr[4]/td[text()='25']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>html/body/div/div[1]/table/tbody/tr[4]/td[text()='25']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>day</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div/div[1]/table/tbody/tr[4]/td[text()='25']</value>
   </webElementProperties>
</WebElementEntity>
